/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame.NonAdmin;

import Class.EMS.*;
import Class.PPS.*;
import Class.PromptComboBoxRenderer;
import Class.TAT.*;
import Class.UMS.*;
import Frame.*;
import java.util.List;
/**
 *
 * @author Charm
 */
public class EmployeeAttendance extends javax.swing.JFrame {
    User user;
    String[] defaultResults = {"0", "0", "0"};
    PayrollService payrollService = new PayrollService();
    
    /**
     * Creates new form AddNewRecord
     */
    public EmployeeAttendance() {
        initComponents();
        

    }
    
    public EmployeeAttendance(User user) {
        this.user = user;
        initComponents();
        
        if (user instanceof NonAdmin){
                jButton3AdminPortal.setVisible(false);
        }
        
        setResultFields(defaultResults);
        jComboBoxAttendancePeriod.setModel(payrollService.getComboBoxModel());
        jComboBoxAttendancePeriod.setRenderer(new PromptComboBoxRenderer("Select Pay Period") );
        jComboBoxAttendancePeriod.setSelectedIndex(-1);
    }
    
    public void setResultFields(String[] results) {
        jLabelTotalHoursResult.setText(results[0]);
        jLabelRegularResult.setText(results[1]);
        jLabelOvertimeResult.setText(results[2]);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton6LogOut = new javax.swing.JButton();
        jButton3AdminPortal = new javax.swing.JButton();
        jButtonInformation = new javax.swing.JButton();
        jButton4Attendance = new javax.swing.JButton();
        jButton4Payslip = new javax.swing.JButton();
        jButtonRequest = new javax.swing.JButton();
        jLabel5EnterDetails = new javax.swing.JLabel();
        jComboBoxAttendancePeriod = new javax.swing.JComboBox<>();
        jLabelTotalHours = new javax.swing.JLabel();
        jLabelRegular = new javax.swing.JLabel();
        jLabelOvertime = new javax.swing.JLabel();
        jLabelTotalHoursResult = new javax.swing.JLabel();
        jLabelRegularResult = new javax.swing.JLabel();
        jLabelOvertimeResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDailyAttendanceList = new javax.swing.JTable();
        jLabelAttendancePeriod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jButton6LogOut.setBackground(new java.awt.Color(0, 102, 153));
        jButton6LogOut.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton6LogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButton6LogOut.setText("Log Out");
        jButton6LogOut.setBorder(null);
        jButton6LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6LogOutActionPerformed(evt);
            }
        });

        jButton3AdminPortal.setBackground(new java.awt.Color(0, 102, 153));
        jButton3AdminPortal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3AdminPortal.setForeground(new java.awt.Color(255, 255, 255));
        jButton3AdminPortal.setText("Admin Portal");
        jButton3AdminPortal.setBorder(null);
        jButton3AdminPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3AdminPortalActionPerformed(evt);
            }
        });

        jButtonInformation.setBackground(new java.awt.Color(0, 102, 153));
        jButtonInformation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonInformation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInformation.setText("Informations");
        jButtonInformation.setBorder(null);
        jButtonInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformationActionPerformed(evt);
            }
        });

        jButton4Attendance.setBackground(new java.awt.Color(0, 102, 153));
        jButton4Attendance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4Attendance.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Attendance.setText("Attendance");
        jButton4Attendance.setBorder(null);
        jButton4Attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4AttendanceActionPerformed(evt);
            }
        });

        jButton4Payslip.setBackground(new java.awt.Color(0, 102, 153));
        jButton4Payslip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4Payslip.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Payslip.setText("Payslip");
        jButton4Payslip.setBorder(null);
        jButton4Payslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4PayslipActionPerformed(evt);
            }
        });

        jButtonRequest.setBackground(new java.awt.Color(0, 102, 153));
        jButtonRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRequest.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRequest.setText("Request");
        jButtonRequest.setBorder(null);
        jButtonRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton3AdminPortal, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButtonInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4Attendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4Payslip, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButtonRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton3AdminPortal)
                .addGap(30, 30, 30)
                .addComponent(jButtonInformation)
                .addGap(30, 30, 30)
                .addComponent(jButton4Attendance)
                .addGap(30, 30, 30)
                .addComponent(jButton4Payslip)
                .addGap(30, 30, 30)
                .addComponent(jButtonRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6LogOut)
                .addContainerGap())
        );

        jLabel5EnterDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5EnterDetails.setText("Employee Attendance");

        jComboBoxAttendancePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAttendancePeriodActionPerformed(evt);
            }
        });

        jLabelTotalHours.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTotalHours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalHours.setText("Total Hours");

        jLabelRegular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRegular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegular.setText("Regular");

        jLabelOvertime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelOvertime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOvertime.setText("Overtime");

        jLabelTotalHoursResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTotalHoursResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalHoursResult.setText("Result");

        jLabelRegularResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRegularResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegularResult.setText("Result");

        jLabelOvertimeResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelOvertimeResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOvertimeResult.setText("Result");

        jTableDailyAttendanceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDailyAttendanceList.setShowGrid(true);
        jTableDailyAttendanceList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableDailyAttendanceList);

        jLabelAttendancePeriod.setText("Attendance Period");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5EnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTotalHours, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTotalHoursResult, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelRegularResult, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelOvertimeResult, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAttendancePeriod)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxAttendancePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5EnterDetails)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAttendancePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAttendancePeriod))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalHours)
                            .addComponent(jLabelRegular)
                            .addComponent(jLabelOvertime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalHoursResult)
                            .addComponent(jLabelRegularResult)
                            .addComponent(jLabelOvertimeResult))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6LogOutActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6LogOutActionPerformed

    private void jButton4AttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4AttendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4AttendanceActionPerformed

    private void jButton4PayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4PayslipActionPerformed
        Access.accessEmployeePayslip(user);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4PayslipActionPerformed

    private void jButtonInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformationActionPerformed
        Access.accessProfilePage(user);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonInformationActionPerformed

    private void jButtonRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRequestActionPerformed

    private void jComboBoxAttendancePeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAttendancePeriodActionPerformed
        if (jComboBoxAttendancePeriod.getSelectedIndex() < 0 || jComboBoxAttendancePeriod.getSelectedItem() == null) {
            return;
        }

        String[] dates = jComboBoxAttendancePeriod.getSelectedItem().toString().split(" : ");
        String startDate = dates[0];
        String endDate = dates[1];

        PayPeriod selectedPayPeriod = new PayPeriod(startDate, endDate);

        AttendanceService dtrManager = new AttendanceService();
        EmployeeService employeeService = new EmployeeService();
        
        jTableDailyAttendanceList.setModel(dtrManager.getAttendanceTableModel(employeeService.getEmployeeInformation(this.user.getEmployeeID()), selectedPayPeriod));

        List<DailyAttendance> employeeAttendance = dtrManager.getFilteredDailyAttendance(employeeService.getEmployeeInformation(this.user.getEmployeeID()), selectedPayPeriod);

        double payableHours = AttendanceCalculator.calculatePayableHours(employeeAttendance);
        double regularHours = AttendanceCalculator.calculateRegularWorkedHours(employeeAttendance);
        double overtime = AttendanceCalculator.calculateApprovedOverTimeHours(employeeAttendance);

        String[] results = {String.valueOf(payableHours),String.valueOf(regularHours),String.valueOf(overtime)};
        setResultFields(results);

    }//GEN-LAST:event_jComboBoxAttendancePeriodActionPerformed

    private void jButton3AdminPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3AdminPortalActionPerformed
        Access.accessCompanyHomePage((Admin) user); 
        this.setVisible(false);
    }//GEN-LAST:event_jButton3AdminPortalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3AdminPortal;
    private javax.swing.JButton jButton4Attendance;
    private javax.swing.JButton jButton4Payslip;
    private javax.swing.JButton jButton6LogOut;
    private javax.swing.JButton jButtonInformation;
    private javax.swing.JButton jButtonRequest;
    private javax.swing.JComboBox<String> jComboBoxAttendancePeriod;
    private javax.swing.JLabel jLabel5EnterDetails;
    private javax.swing.JLabel jLabelAttendancePeriod;
    private javax.swing.JLabel jLabelOvertime;
    private javax.swing.JLabel jLabelOvertimeResult;
    private javax.swing.JLabel jLabelRegular;
    private javax.swing.JLabel jLabelRegularResult;
    private javax.swing.JLabel jLabelTotalHours;
    private javax.swing.JLabel jLabelTotalHoursResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDailyAttendanceList;
    // End of variables declaration//GEN-END:variables
}
