/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame.NonAdmin;

import Class.EMS.*;
import Class.PPS.*;
import Class.PromptComboBoxRenderer;
import Class.TAT.*;
import Class.UMS.*;
import Frame.*;
import java.time.format.DateTimeFormatter;
import java.util.List;
/**
 *
 * @author Charm
 */
public class EmployeePayslip extends javax.swing.JFrame {
    DateTimeFormatter formatterDate1  = DateTimeFormatter.ofPattern("MMMM dd");
    DateTimeFormatter formatterDate2  = DateTimeFormatter.ofPattern("MMMM dd yyyy");
    User user;
    PayrollService payrollService = new PayrollService();
    EmployeeService employeeService = new EmployeeService();
    AttendanceService attendanceService = new AttendanceService();
    
    /**
     * Creates new form AddNewRecord
     */
    public EmployeePayslip() {
        initComponents();
        

    }
    
    public EmployeePayslip(User user) {
        initComponents();
        this.user = user;
        Employee employee = employeeService.getEmployeeInformation(this.user.getEmployeeID());
        
        if (user instanceof NonAdmin){
                jButton3AdminPortal.setVisible(false);
        }
        
        jLabelInputID5.setText(user.getEmployeeID());      
        jLabelInputName5.setText(employee.getFirstName() + " " + employee.getLastName()); 
        jLabelInputPayPeriod5.setText("");
        
        jComboBoxAttendancePeriod.setModel(payrollService.getComboBoxModel());
        jComboBoxAttendancePeriod.setRenderer(new PromptComboBoxRenderer("Select Pay Period") );
        jComboBoxAttendancePeriod.setSelectedIndex(-1);
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton6LogOut = new javax.swing.JButton();
        jButton3AdminPortal = new javax.swing.JButton();
        jButtonInformation = new javax.swing.JButton();
        jButton4Payroll2 = new javax.swing.JButton();
        jButton4Payroll3 = new javax.swing.JButton();
        jButtonRequest = new javax.swing.JButton();
        jLabel5EnterDetails = new javax.swing.JLabel();
        jPanelEmployeeInformation5 = new javax.swing.JPanel();
        jLabelEmployeeID5 = new javax.swing.JLabel();
        jLabelInputID5 = new javax.swing.JLabel();
        jLabelName5 = new javax.swing.JLabel();
        jLabelInputName5 = new javax.swing.JLabel();
        jLabelPayPeriod5 = new javax.swing.JLabel();
        jLabelInputPayPeriod5 = new javax.swing.JLabel();
        jPanelEarnings = new javax.swing.JPanel();
        jLabelBasicSalary2 = new javax.swing.JLabel();
        jTextFieldBasicSalary2 = new javax.swing.JTextField();
        jTextFieldRiceSubsidy = new javax.swing.JTextField();
        jLabelRiceSubsidy = new javax.swing.JLabel();
        jLabelPhoneAllowance = new javax.swing.JLabel();
        jTextFieldPhoneAllowance = new javax.swing.JTextField();
        jLabelClothingAllowance = new javax.swing.JLabel();
        jTextFieldClothingAllowance = new javax.swing.JTextField();
        jLabelHoursWorked = new javax.swing.JLabel();
        jLabelHourlyRate = new javax.swing.JLabel();
        jTextFieldHoursWorked = new javax.swing.JTextField();
        jTextFieldHourlyRate = new javax.swing.JTextField();
        jLabelBasicSalary1 = new javax.swing.JLabel();
        jTextFieldBasicSalary1 = new javax.swing.JTextField();
        jLabelGrossSalary = new javax.swing.JLabel();
        jTextFieldGrossSalary = new javax.swing.JTextField();
        jPanelDeduction = new javax.swing.JPanel();
        jLabelWitholdingTax = new javax.swing.JLabel();
        jTextFieldWitholdingTax = new javax.swing.JTextField();
        jTextFieldSSS = new javax.swing.JTextField();
        jLabelSSS = new javax.swing.JLabel();
        jLabelPhilHealth = new javax.swing.JLabel();
        jTextFieldPhilHealth = new javax.swing.JTextField();
        jLabelPagIBIG = new javax.swing.JLabel();
        jTextFieldPagIBIG = new javax.swing.JTextField();
        jLabelTotalDeductions = new javax.swing.JLabel();
        jTextFieldTotalDeductions = new javax.swing.JTextField();
        jTextFieldNetSalary = new javax.swing.JTextField();
        jLabelNetSalary = new javax.swing.JLabel();
        jComboBoxAttendancePeriod = new javax.swing.JComboBox<>();
        jLabelAttendancePeriod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jButton6LogOut.setBackground(new java.awt.Color(0, 102, 153));
        jButton6LogOut.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton6LogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButton6LogOut.setText("Log Out");
        jButton6LogOut.setBorder(null);
        jButton6LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6LogOutActionPerformed(evt);
            }
        });

        jButton3AdminPortal.setBackground(new java.awt.Color(0, 102, 153));
        jButton3AdminPortal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3AdminPortal.setForeground(new java.awt.Color(255, 255, 255));
        jButton3AdminPortal.setText("Admin Portal");
        jButton3AdminPortal.setBorder(null);
        jButton3AdminPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3AdminPortalActionPerformed(evt);
            }
        });

        jButtonInformation.setBackground(new java.awt.Color(0, 102, 153));
        jButtonInformation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonInformation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInformation.setText("Informations");
        jButtonInformation.setBorder(null);
        jButtonInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformationActionPerformed(evt);
            }
        });

        jButton4Payroll2.setBackground(new java.awt.Color(0, 102, 153));
        jButton4Payroll2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4Payroll2.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Payroll2.setText("Attendance");
        jButton4Payroll2.setBorder(null);
        jButton4Payroll2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4Payroll2ActionPerformed(evt);
            }
        });

        jButton4Payroll3.setBackground(new java.awt.Color(0, 102, 153));
        jButton4Payroll3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4Payroll3.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Payroll3.setText("Payslip");
        jButton4Payroll3.setBorder(null);
        jButton4Payroll3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4Payroll3ActionPerformed(evt);
            }
        });

        jButtonRequest.setBackground(new java.awt.Color(0, 102, 153));
        jButtonRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRequest.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRequest.setText("Request");
        jButtonRequest.setBorder(null);
        jButtonRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton3AdminPortal, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButtonInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4Payroll2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4Payroll3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButtonRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton3AdminPortal)
                .addGap(30, 30, 30)
                .addComponent(jButtonInformation)
                .addGap(30, 30, 30)
                .addComponent(jButton4Payroll2)
                .addGap(30, 30, 30)
                .addComponent(jButton4Payroll3)
                .addGap(30, 30, 30)
                .addComponent(jButtonRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6LogOut)
                .addContainerGap())
        );

        jLabel5EnterDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5EnterDetails.setText("Employee Payslip");

        jLabelEmployeeID5.setText("Employee ID:");

        jLabelInputID5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInputID5.setText("jLabel3");

        jLabelName5.setText("Name:");

        jLabelInputName5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInputName5.setText("jLabel5");

        jLabelPayPeriod5.setText("Pay Period:");

        jLabelInputPayPeriod5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInputPayPeriod5.setText("jLabel16");

        javax.swing.GroupLayout jPanelEmployeeInformation5Layout = new javax.swing.GroupLayout(jPanelEmployeeInformation5);
        jPanelEmployeeInformation5.setLayout(jPanelEmployeeInformation5Layout);
        jPanelEmployeeInformation5Layout.setHorizontalGroup(
            jPanelEmployeeInformation5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeeInformation5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmployeeInformation5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmployeeInformation5Layout.createSequentialGroup()
                        .addComponent(jLabelName5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInputName5)
                        .addGap(0, 464, Short.MAX_VALUE))
                    .addGroup(jPanelEmployeeInformation5Layout.createSequentialGroup()
                        .addComponent(jLabelEmployeeID5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInputID5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPayPeriod5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInputPayPeriod5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelEmployeeInformation5Layout.setVerticalGroup(
            jPanelEmployeeInformation5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeeInformation5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmployeeInformation5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPayPeriod5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelEmployeeInformation5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEmployeeID5)
                        .addComponent(jLabelInputID5)
                        .addComponent(jLabelInputPayPeriod5)))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmployeeInformation5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName5)
                    .addComponent(jLabelInputName5))
                .addContainerGap())
        );

        jPanelEarnings.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Earnings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabelBasicSalary2.setText("Basic Salary:");

        jTextFieldBasicSalary2.setEditable(false);
        jTextFieldBasicSalary2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldBasicSalary2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextFieldRiceSubsidy.setEditable(false);
        jTextFieldRiceSubsidy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRiceSubsidy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelRiceSubsidy.setText("Rice Subsidy:");

        jLabelPhoneAllowance.setText("Phone Allowance:");

        jTextFieldPhoneAllowance.setEditable(false);
        jTextFieldPhoneAllowance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPhoneAllowance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelClothingAllowance.setText("Clothing Allowance:");

        jTextFieldClothingAllowance.setEditable(false);
        jTextFieldClothingAllowance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldClothingAllowance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelHoursWorked.setText("Hours Worked:");

        jLabelHourlyRate.setText("Hourly Rate:");

        jTextFieldHoursWorked.setEditable(false);
        jTextFieldHoursWorked.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldHoursWorked.setEnabled(false);

        jTextFieldHourlyRate.setEditable(false);
        jTextFieldHourlyRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldHourlyRate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelBasicSalary1.setText("Basic Salary:");

        jTextFieldBasicSalary1.setEditable(false);
        jTextFieldBasicSalary1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldBasicSalary1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelGrossSalary.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabelGrossSalary.setText("Gross Salary:");

        jTextFieldGrossSalary.setEditable(false);
        jTextFieldGrossSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldGrossSalary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldGrossSalary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelEarningsLayout = new javax.swing.GroupLayout(jPanelEarnings);
        jPanelEarnings.setLayout(jPanelEarningsLayout);
        jPanelEarningsLayout.setHorizontalGroup(
            jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEarningsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEarningsLayout.createSequentialGroup()
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelBasicSalary1)
                            .addComponent(jLabelHoursWorked)
                            .addComponent(jLabelHourlyRate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHourlyRate, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldBasicSalary1)
                            .addComponent(jTextFieldHoursWorked))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEarningsLayout.createSequentialGroup()
                                .addComponent(jLabelPhoneAllowance)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEarningsLayout.createSequentialGroup()
                                .addComponent(jLabelRiceSubsidy)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEarningsLayout.createSequentialGroup()
                                .addComponent(jLabelBasicSalary2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldBasicSalary2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEarningsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEarningsLayout.createSequentialGroup()
                                .addComponent(jLabelClothingAllowance)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEarningsLayout.createSequentialGroup()
                                .addComponent(jLabelGrossSalary)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelEarningsLayout.setVerticalGroup(
            jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEarningsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEarningsLayout.createSequentialGroup()
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBasicSalary2)
                            .addComponent(jTextFieldBasicSalary2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRiceSubsidy)
                            .addComponent(jTextFieldRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPhoneAllowance)
                            .addComponent(jTextFieldPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEarningsLayout.createSequentialGroup()
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHoursWorked)
                            .addComponent(jTextFieldHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHourlyRate)
                            .addComponent(jTextFieldHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBasicSalary1)
                            .addComponent(jTextFieldBasicSalary1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClothingAllowance)
                    .addComponent(jTextFieldClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGrossSalary)
                    .addComponent(jTextFieldGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDeduction.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deductions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabelWitholdingTax.setText("Witholding Tax:");

        jTextFieldWitholdingTax.setEditable(false);
        jTextFieldWitholdingTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldWitholdingTax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextFieldSSS.setEditable(false);
        jTextFieldSSS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSSS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelSSS.setText("SSS:");

        jLabelPhilHealth.setText("PhilHealth:");

        jTextFieldPhilHealth.setEditable(false);
        jTextFieldPhilHealth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPhilHealth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelPagIBIG.setText("Pag-IBIG:");

        jTextFieldPagIBIG.setEditable(false);
        jTextFieldPagIBIG.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPagIBIG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelTotalDeductions.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabelTotalDeductions.setText("Total Deductions:");

        jTextFieldTotalDeductions.setEditable(false);
        jTextFieldTotalDeductions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTotalDeductions.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanelDeductionLayout = new javax.swing.GroupLayout(jPanelDeduction);
        jPanelDeduction.setLayout(jPanelDeductionLayout);
        jPanelDeductionLayout.setHorizontalGroup(
            jPanelDeductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeductionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotalDeductions)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelDeductionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelDeductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeductionLayout.createSequentialGroup()
                        .addComponent(jLabelPhilHealth)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeductionLayout.createSequentialGroup()
                        .addComponent(jLabelSSS)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeductionLayout.createSequentialGroup()
                        .addComponent(jLabelWitholdingTax)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldWitholdingTax, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeductionLayout.createSequentialGroup()
                        .addComponent(jLabelPagIBIG)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPagIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDeductionLayout.setVerticalGroup(
            jPanelDeductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeductionLayout.createSequentialGroup()
                .addGroup(jPanelDeductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWitholdingTax)
                    .addComponent(jTextFieldWitholdingTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSSS)
                    .addComponent(jTextFieldSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhilHealth)
                    .addComponent(jTextFieldPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPagIBIG)
                    .addComponent(jTextFieldPagIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelDeductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalDeductions)
                    .addComponent(jTextFieldTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTextFieldNetSalary.setEditable(false);
        jTextFieldNetSalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldNetSalary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabelNetSalary.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelNetSalary.setText("Net Salary:");

        jComboBoxAttendancePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAttendancePeriodActionPerformed(evt);
            }
        });

        jLabelAttendancePeriod.setText("Pay Period");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5EnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelEarnings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelEmployeeInformation5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelDeduction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNetSalary)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelAttendancePeriod)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxAttendancePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5EnterDetails)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAttendancePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAttendancePeriod))
                        .addGap(10, 10, 10)
                        .addComponent(jPanelEmployeeInformation5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelEarnings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNetSalary))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6LogOutActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6LogOutActionPerformed

    private void jButton4Payroll2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4Payroll2ActionPerformed
        Access.accessEmployeeAttendance(user);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4Payroll2ActionPerformed

    private void jButton4Payroll3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4Payroll3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4Payroll3ActionPerformed

    private void jButtonInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformationActionPerformed
        Access.accessProfilePage(user);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonInformationActionPerformed

    private void jButtonRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRequestActionPerformed

    private void jComboBoxAttendancePeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAttendancePeriodActionPerformed
        if (jComboBoxAttendancePeriod.getSelectedIndex() < 0 || jComboBoxAttendancePeriod.getSelectedItem() == null) {
            return;
        }

        String[] dates = jComboBoxAttendancePeriod.getSelectedItem().toString().split(" : ");
        String startDate = dates[0];
        String endDate = dates[1];

        PayPeriod selectedPayPeriod = new PayPeriod(startDate, endDate);
        jLabelInputPayPeriod5.setText(selectedPayPeriod.getStartDate().format(formatterDate1) + " - " + selectedPayPeriod.getEndDate().format(formatterDate2));
        
        Employee employee = employeeService.getEmployeeInformation(this.user.getEmployeeID());
        double payableHours = AttendanceCalculator.calculatePayableHours(attendanceService.getFilteredDailyAttendance(employee, selectedPayPeriod));
        double hourlyRate = Double.parseDouble(employee.getHourlyRate().replace(",", ""));
        double rice = Double.parseDouble(employee.getRiceSubsidy().replace(",", ""));
        double phone = Double.parseDouble(employee.getPhoneAllowance().replace(",", ""));
        double clothing = Double.parseDouble(employee.getClothingAllowance().replace(",", ""));
        double basicSalary = SalaryCalculator.calculateBasicSalary(payableHours, Double.parseDouble(employee.getHourlyRate().replace(",", "")));
        double totalAllowance = AllowanceCalculator.calculateTotalAllowance(Double.parseDouble(employee.getRiceSubsidy().replace(",", "")),
                                                                            Double.parseDouble(employee.getPhoneAllowance().replace(",", "")), 
                                                                            Double.parseDouble(employee.getClothingAllowance().replace(",", "")));
        double grossSalary = SalaryCalculator.calculateGrossSalary(basicSalary, totalAllowance);
        double sss = DeductionCalculator.calculateSSS(grossSalary);
        double philhealth = DeductionCalculator.calculatePhilHealth(grossSalary);            
        double pagibig = DeductionCalculator.calculatePagIbig(grossSalary);
        double govermentContribution = DeductionCalculator.calculateGovernmentContribution(sss, philhealth, pagibig);
        double tax = TaxCalculator.calculateWithHoldingTax(grossSalary, govermentContribution);
        double totalDeduction = DeductionCalculator.calculateTotalDeductions(govermentContribution, tax);
        double netSalary = SalaryCalculator.calculateNetSalary(grossSalary, totalDeduction, tax);
        
        setEarningResults(new Object[] {payableHours, hourlyRate, basicSalary, rice, phone, clothing, grossSalary});
        setDeductionResults(new Object[] {tax, sss, philhealth, pagibig, totalDeduction});
        setNetSalaryResult(netSalary);
        
        
    }//GEN-LAST:event_jComboBoxAttendancePeriodActionPerformed

    private void jButton3AdminPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3AdminPortalActionPerformed
        Access.accessCompanyHomePage((Admin) user); 
        this.setVisible(false);
    }//GEN-LAST:event_jButton3AdminPortalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3AdminPortal;
    private javax.swing.JButton jButton4Payroll2;
    private javax.swing.JButton jButton4Payroll3;
    private javax.swing.JButton jButton6LogOut;
    private javax.swing.JButton jButtonInformation;
    private javax.swing.JButton jButtonRequest;
    private javax.swing.JComboBox<String> jComboBoxAttendancePeriod;
    private javax.swing.JLabel jLabel5EnterDetails;
    private javax.swing.JLabel jLabelAttendancePeriod;
    private javax.swing.JLabel jLabelBasicSalary1;
    private javax.swing.JLabel jLabelBasicSalary2;
    private javax.swing.JLabel jLabelClothingAllowance;
    private javax.swing.JLabel jLabelEmployeeID5;
    private javax.swing.JLabel jLabelGrossSalary;
    private javax.swing.JLabel jLabelHourlyRate;
    private javax.swing.JLabel jLabelHoursWorked;
    private javax.swing.JLabel jLabelInputID5;
    private javax.swing.JLabel jLabelInputName5;
    private javax.swing.JLabel jLabelInputPayPeriod5;
    private javax.swing.JLabel jLabelName5;
    private javax.swing.JLabel jLabelNetSalary;
    private javax.swing.JLabel jLabelPagIBIG;
    private javax.swing.JLabel jLabelPayPeriod5;
    private javax.swing.JLabel jLabelPhilHealth;
    private javax.swing.JLabel jLabelPhoneAllowance;
    private javax.swing.JLabel jLabelRiceSubsidy;
    private javax.swing.JLabel jLabelSSS;
    private javax.swing.JLabel jLabelTotalDeductions;
    private javax.swing.JLabel jLabelWitholdingTax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDeduction;
    private javax.swing.JPanel jPanelEarnings;
    private javax.swing.JPanel jPanelEmployeeInformation5;
    private javax.swing.JTextField jTextFieldBasicSalary1;
    private javax.swing.JTextField jTextFieldBasicSalary2;
    private javax.swing.JTextField jTextFieldClothingAllowance;
    private javax.swing.JTextField jTextFieldGrossSalary;
    private javax.swing.JTextField jTextFieldHourlyRate;
    private javax.swing.JTextField jTextFieldHoursWorked;
    private javax.swing.JTextField jTextFieldNetSalary;
    private javax.swing.JTextField jTextFieldPagIBIG;
    private javax.swing.JTextField jTextFieldPhilHealth;
    private javax.swing.JTextField jTextFieldPhoneAllowance;
    private javax.swing.JTextField jTextFieldRiceSubsidy;
    private javax.swing.JTextField jTextFieldSSS;
    private javax.swing.JTextField jTextFieldTotalDeductions;
    private javax.swing.JTextField jTextFieldWitholdingTax;
    // End of variables declaration//GEN-END:variables
    
    public void setEarningResults(Object[] payrollData){
        jTextFieldHoursWorked.setText(payrollData[0].toString());
        jTextFieldHourlyRate.setText(payrollData[1].toString());
        jTextFieldBasicSalary1.setText(payrollData[2].toString());
        jTextFieldBasicSalary2.setText(payrollData[2].toString());
        jTextFieldRiceSubsidy.setText(payrollData[3].toString());
        jTextFieldPhoneAllowance.setText(payrollData[4].toString());
        jTextFieldClothingAllowance.setText(payrollData[5].toString());
        jTextFieldGrossSalary.setText(payrollData[6].toString());
    }
    
    public void setDeductionResults(Object[] payrollData){
        jTextFieldWitholdingTax.setText(payrollData[0].toString());
        jTextFieldSSS.setText(payrollData[1].toString());
        jTextFieldPhilHealth.setText(payrollData[2].toString());
        jTextFieldPagIBIG.setText(payrollData[3].toString());
        jTextFieldTotalDeductions.setText(payrollData[4].toString());
    }
    
    public void setNetSalaryResult(double payrollData){
        jTextFieldNetSalary.setText(String.valueOf(payrollData));
    }
}
