/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import Class.Product;
import Class.Service;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author 63909
 */
public class SaleForm extends javax.swing.JFrame {

    /**
     * Creates new form PhoneSoldForm
     */
    public SaleForm() {
        initComponents();
        jLabelServicePrice.setText("0");
        jLabelErrorMessage.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelErrorMessage.setVisible(false);
        jSpinnerQuantity.setEnabled(false);
        jLabelTotalSale.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFormHeader = new javax.swing.JLabel();
        jLabelItem = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelServicePrice = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jSpinnerQuantity = new javax.swing.JSpinner();
        jLabelUnits = new javax.swing.JLabel();
        jLabelTotalSale = new javax.swing.JLabel();
        jLabelTotalAmount = new javax.swing.JLabel();
        jComboBoxItem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxService = new javax.swing.JComboBox<>();
        jLabelErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFormHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFormHeader.setText("Sales Form");

        jLabelItem.setText("Select Item:");

        jLabelPrice.setText("Price:");

        jLabelServicePrice.setText("jLabelPhonePrice");

        jLabelQuantity.setText("Quantity:");

        jSpinnerQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQuantityStateChanged(evt);
            }
        });

        jLabelUnits.setText("unit/s");

        jLabelTotalSale.setText("jLabelTotalSale");

        jLabelTotalAmount.setText("Total Amount");

        jComboBoxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Sale:");

        jComboBoxService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product", "Service" }));
        jComboBoxService.setSelectedIndex(-1);
        jComboBoxService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServiceActionPerformed(evt);
            }
        });

        jLabelErrorMessage.setForeground(java.awt.Color.red);
        jLabelErrorMessage.setText("jLabelErrorMessage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFormHeader)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelQuantity)
                            .addComponent(jLabelTotalAmount)
                            .addComponent(jLabelPrice)
                            .addComponent(jLabelItem)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxService, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxItem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelServicePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinnerQuantity)
                                    .addComponent(jLabelTotalSale, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUnits))))
                    .addComponent(jLabelErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelFormHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice)
                    .addComponent(jLabelServicePrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity)
                    .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnits))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTotalSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelErrorMessage)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServiceActionPerformed
        if(jComboBoxService.getSelectedItem().equals("Product")){
            jComboBoxItem.removeAllItems();            
            jComboBoxItem.addItem("Iphone");
            jComboBoxItem.addItem("Samsung");
            jComboBoxItem.addItem("Honor");
            jComboBoxItem.setSelectedIndex(-1);
            jSpinnerQuantity.setValue(0);
            jSpinnerQuantity.setEnabled(false);
        }
        if(jComboBoxService.getSelectedItem().equals("Service")){
            jComboBoxItem.removeAllItems();
            jComboBoxItem.addItem("Screen replacement");
            jComboBoxItem.addItem("Battery replacement");
            jComboBoxItem.addItem("Phone camera repair");
            jComboBoxItem.setSelectedIndex(-1);
            jSpinnerQuantity.setValue(0);
            jSpinnerQuantity.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxServiceActionPerformed

    private void jComboBoxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemActionPerformed
        Map<String, Integer> items = new HashMap<>();
        items.put("Iphone", 50000);
        items.put("Samsung", 30000);
        items.put("Honor", 10000);
        items.put("Screen replacement", 5000);
        items.put("Battery replacement", 7000);
        items.put("Phone camera repair", 10000);
        
        jSpinnerQuantity.setValue(0);
        
        try{
            String price = Integer.toString(items.get(jComboBoxItem.getSelectedItem().toString()));
            jLabelServicePrice.setText(price);
        }
        catch(NullPointerException e){
            jLabelServicePrice.setText("0");
        }        
        
        jSpinnerQuantity.setEnabled(true);

    }//GEN-LAST:event_jComboBoxItemActionPerformed

    private void jSpinnerQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQuantityStateChanged
        
        try{
            if(jComboBoxService.getSelectedItem().equals("Product")){
                Product product = new Product(jComboBoxItem.getSelectedItem().toString(),Integer.parseInt(jLabelServicePrice.getText()));
                jLabelTotalSale.setText(String.valueOf(product.computeTotalSale((int) jSpinnerQuantity.getValue())));
            }
            else if (jComboBoxService.getSelectedItem().equals("Service")){
                Service service = new Service(jComboBoxItem.getSelectedItem().toString(),Integer.parseInt(jLabelServicePrice.getText()));
                jLabelTotalSale.setText(String.valueOf(service.computeTotalSale((int) jSpinnerQuantity.getValue())));
            }
        }
        catch(NullPointerException e){
            jSpinnerQuantity.setValue(0);
        }
    }//GEN-LAST:event_jSpinnerQuantityStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxItem;
    private javax.swing.JComboBox<String> jComboBoxService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JLabel jLabelFormHeader;
    private javax.swing.JLabel jLabelItem;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelServicePrice;
    private javax.swing.JLabel jLabelTotalAmount;
    private javax.swing.JLabel jLabelTotalSale;
    private javax.swing.JLabel jLabelUnits;
    private javax.swing.JSpinner jSpinnerQuantity;
    // End of variables declaration//GEN-END:variables
}
