/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import Class.UMS.CurrentUser;
import Class.UMS.User;

/**
 *
 * @author Charm
 */
public class EmployeeDashboard extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDashboard
     * @param user The logged-in user 
     */
    private User currentUser;  // Declare currentUser
    
    public EmployeeDashboard(User user) {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1RequestCenter = new javax.swing.JButton();
        jButton3AttendanceRecord = new javax.swing.JButton();
        jButton4CompanyPortal = new javax.swing.JButton();
        jButton6LogOut = new javax.swing.JButton();
        jButton3TimeClock = new javax.swing.JButton();
        jButton4Payslip1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jButton1RequestCenter.setBackground(new java.awt.Color(0, 102, 153));
        jButton1RequestCenter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1RequestCenter.setForeground(new java.awt.Color(255, 255, 255));
        jButton1RequestCenter.setText("Request Center");
        jButton1RequestCenter.setBorder(null);
        jButton1RequestCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RequestCenterActionPerformed(evt);
            }
        });

        jButton3AttendanceRecord.setBackground(new java.awt.Color(0, 102, 153));
        jButton3AttendanceRecord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3AttendanceRecord.setForeground(new java.awt.Color(255, 255, 255));
        jButton3AttendanceRecord.setText("Attendance Record");
        jButton3AttendanceRecord.setBorder(null);
        jButton3AttendanceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3AttendanceRecordActionPerformed(evt);
            }
        });

        jButton4CompanyPortal.setBackground(new java.awt.Color(0, 102, 153));
        jButton4CompanyPortal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4CompanyPortal.setForeground(new java.awt.Color(255, 255, 255));
        jButton4CompanyPortal.setText("Company Portal");
        jButton4CompanyPortal.setBorder(null);
        jButton4CompanyPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4CompanyPortalActionPerformed(evt);
            }
        });

        jButton6LogOut.setBackground(new java.awt.Color(0, 102, 153));
        jButton6LogOut.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton6LogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButton6LogOut.setText("Log Out");
        jButton6LogOut.setBorder(null);
        jButton6LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6LogOutActionPerformed(evt);
            }
        });

        jButton3TimeClock.setBackground(new java.awt.Color(0, 102, 153));
        jButton3TimeClock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3TimeClock.setForeground(new java.awt.Color(255, 255, 255));
        jButton3TimeClock.setText("Time Clock");
        jButton3TimeClock.setBorder(null);

        jButton4Payslip1.setBackground(new java.awt.Color(0, 102, 153));
        jButton4Payslip1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4Payslip1.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Payslip1.setText("Payslip");
        jButton4Payslip1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1RequestCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3AttendanceRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4CompanyPortal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton6LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton3TimeClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4Payslip1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton3TimeClock)
                .addGap(37, 37, 37)
                .addComponent(jButton3AttendanceRecord)
                .addGap(37, 37, 37)
                .addComponent(jButton1RequestCenter)
                .addGap(36, 36, 36)
                .addComponent(jButton4Payslip1)
                .addGap(44, 44, 44)
                .addComponent(jButton4CompanyPortal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jButton6LogOut)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(672, 672, 672))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6LogOutActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6LogOutActionPerformed

    private void jButton3AttendanceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3AttendanceRecordActionPerformed
        AttendanceRecord attendanceRecord = new AttendanceRecord();
        attendanceRecord.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3AttendanceRecordActionPerformed

    private void jButton1RequestCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RequestCenterActionPerformed
        RequestCenter requestCenter = new RequestCenter((CurrentUser) currentUser);
        requestCenter.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1RequestCenterActionPerformed

    private void jButton4CompanyPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4CompanyPortalActionPerformed
        CompanyHomePage companyHomePage = new CompanyHomePage (currentUser);
        companyHomePage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4CompanyPortalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1RequestCenter;
    private javax.swing.JButton jButton3AttendanceRecord;
    private javax.swing.JButton jButton3TimeClock;
    private javax.swing.JButton jButton4CompanyPortal;
    private javax.swing.JButton jButton4Payslip1;
    private javax.swing.JButton jButton6LogOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
