/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

/**
 *
 * @author Charm
 */
import Class.PPS.*;
import Class.UMS.*;
import java.text.DecimalFormat;
import java.time.format.DateTimeFormatter;

public class PayrollSummaryPage extends javax.swing.JFrame {
    DateTimeFormatter formatterDate1  = DateTimeFormatter.ofPattern("MMMM dd");
    DateTimeFormatter formatterDate2  = DateTimeFormatter.ofPattern("MMMM dd yyyy");
    private static DecimalFormat decimalFormat = new DecimalFormat("0.00");
    Admin admin;
    PayPeriod payrollPayPeriod;
    PayrollService payrollService = new PayrollService();
    PayrollSummary payrollSummary;
    
    public PayrollSummaryPage() {
        initComponents();        

    }
    
    public PayrollSummaryPage(PayPeriod payPeriod) {
        initComponents();
        this.payrollPayPeriod = payPeriod;
        jPanel1.setVisible(false);
        
        jLabelPayPeriod.setText("Payroll Summary for the period of " + payPeriod.getStartDate().format(formatterDate1) + " - " + payPeriod.getEndDate().format(formatterDate2));
        payrollSummary = PayrollCalculator.calculatePayrollSummary(payrollService.generatePayrollRecord(payPeriod));
        jLabelTotalBasicSalaryResult.setText(Double.toString(payrollSummary.getTotalBasicSalary()));
        jLabelTotalGrossSalaryResult.setText(Double.toString(payrollSummary.getTotalGrossSalary()));        
        jLabelTotalGovernmentContributionResult.setText(Double.toString(payrollSummary.getTotalGovernmentContribution()));
        jLabelTotalWithholdingTaxResult.setText(Double.toString(payrollSummary.getTotalWithholdingTax()));
        jLabelTotalDeductionResult.setText(Double.toString(payrollSummary.getTotalDeductions()));
        jLabelTotalNetSalaryResult.setText(Double.toString(payrollSummary.getTotalNetSalary()));

        
    }

    public PayrollSummaryPage(Admin admin, PayPeriod payPeriod) {
        initComponents();
        this.admin = admin;
        this.payrollPayPeriod = payPeriod;
        jPanel1.setVisible(false);
        
        jLabelPayPeriod.setText("Payroll Summary for the period of " + payPeriod.getStartDate().format(formatterDate1) + " - " + payPeriod.getEndDate().format(formatterDate2));
        payrollSummary = PayrollCalculator.calculatePayrollSummary(payrollService.generatePayrollRecord(payPeriod));
        jLabelTotalBasicSalaryResult.setText(Double.toString(payrollSummary.getTotalBasicSalary()));
        jLabelTotalGrossSalaryResult.setText(Double.toString(payrollSummary.getTotalGrossSalary()));        
        jLabelTotalGovernmentContributionResult.setText(Double.toString(payrollSummary.getTotalGovernmentContribution()));
        jLabelTotalWithholdingTaxResult.setText(Double.toString(payrollSummary.getTotalWithholdingTax()));
        jLabelTotalDeductionResult.setText(Double.toString(payrollSummary.getTotalDeductions()));
        jLabelTotalNetSalaryResult.setText(Double.toString(payrollSummary.getTotalNetSalary()));

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton1EmployeeInformation = new javax.swing.JButton();
        jButton3EmployeeRequest = new javax.swing.JButton();
        jButton4Payroll = new javax.swing.JButton();
        jButton6LogOut = new javax.swing.JButton();
        jButton3SelfServicePortal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTotalBasicSalary = new javax.swing.JLabel();
        jLabelTotalBasicSalaryResult = new javax.swing.JLabel();
        jLabelTotalGrossSalary = new javax.swing.JLabel();
        jLabelTotalGrossSalaryResult = new javax.swing.JLabel();
        jLabelTotalGovernmentContribution = new javax.swing.JLabel();
        jLabelTotalGovernmentContributionResult = new javax.swing.JLabel();
        jLabelTotalWithholdingTax = new javax.swing.JLabel();
        jLabelTotalWithholdingTaxResult = new javax.swing.JLabel();
        jLabelTotalDeduction = new javax.swing.JLabel();
        jLabelTotalDeductionResult = new javax.swing.JLabel();
        jLabelTotalNetSalary = new javax.swing.JLabel();
        jLabelTotalNetSalaryResult = new javax.swing.JLabel();
        jLabelPayPeriod = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        jButton5.setBackground(new java.awt.Color(0, 102, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Payroll");
        jButton5.setBorder(null);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jButton1EmployeeInformation.setBackground(new java.awt.Color(0, 102, 153));
        jButton1EmployeeInformation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1EmployeeInformation.setForeground(new java.awt.Color(255, 255, 255));
        jButton1EmployeeInformation.setText("Employee Information");
        jButton1EmployeeInformation.setBorder(null);
        jButton1EmployeeInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EmployeeInformationActionPerformed(evt);
            }
        });

        jButton3EmployeeRequest.setBackground(new java.awt.Color(0, 102, 153));
        jButton3EmployeeRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3EmployeeRequest.setForeground(new java.awt.Color(255, 255, 255));
        jButton3EmployeeRequest.setText("Employee Request");
        jButton3EmployeeRequest.setBorder(null);

        jButton4Payroll.setBackground(new java.awt.Color(0, 102, 153));
        jButton4Payroll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4Payroll.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Payroll.setText("Payroll");
        jButton4Payroll.setBorder(null);

        jButton6LogOut.setBackground(new java.awt.Color(0, 102, 153));
        jButton6LogOut.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton6LogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButton6LogOut.setText("Log Out");
        jButton6LogOut.setBorder(null);
        jButton6LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6LogOutActionPerformed(evt);
            }
        });

        jButton3SelfServicePortal.setBackground(new java.awt.Color(0, 102, 153));
        jButton3SelfServicePortal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3SelfServicePortal.setForeground(new java.awt.Color(255, 255, 255));
        jButton3SelfServicePortal.setText("Self Service Portal");
        jButton3SelfServicePortal.setBorder(null);
        jButton3SelfServicePortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3SelfServicePortalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1EmployeeInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3EmployeeRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4Payroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton6LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton3SelfServicePortal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton3SelfServicePortal)
                .addGap(37, 37, 37)
                .addComponent(jButton3EmployeeRequest)
                .addGap(37, 37, 37)
                .addComponent(jButton1EmployeeInformation)
                .addGap(34, 34, 34)
                .addComponent(jButton4Payroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jButton6LogOut)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jLabelTotalBasicSalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotalBasicSalary.setText("Total Basic Salary: ");

        jLabelTotalBasicSalaryResult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalBasicSalaryResult.setText("Result");

        jLabelTotalGrossSalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotalGrossSalary.setText("Total Gross Salary: ");

        jLabelTotalGrossSalaryResult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalGrossSalaryResult.setText("Result");

        jLabelTotalGovernmentContribution.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotalGovernmentContribution.setText("Total Government Contribution: ");

        jLabelTotalGovernmentContributionResult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalGovernmentContributionResult.setText("Result");

        jLabelTotalWithholdingTax.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotalWithholdingTax.setText("Total Withholding Tax: ");

        jLabelTotalWithholdingTaxResult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalWithholdingTaxResult.setText("Result");

        jLabelTotalDeduction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotalDeduction.setText("Total Deduction: ");

        jLabelTotalDeductionResult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalDeductionResult.setText("Result");

        jLabelTotalNetSalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotalNetSalary.setText("Total Net Salary: ");

        jLabelTotalNetSalaryResult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalNetSalaryResult.setText("Result");

        jLabelPayPeriod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPayPeriod.setText("Payroll Summary for the period of PayPeriod");

        jButtonNext.setText("Submit");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelTotalNetSalary)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelTotalNetSalaryResult))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTotalDeduction)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTotalDeductionResult))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelTotalBasicSalary)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelTotalBasicSalaryResult))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelTotalGrossSalary)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelTotalGrossSalaryResult)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTotalGovernmentContribution)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTotalGovernmentContributionResult))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTotalWithholdingTax)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTotalWithholdingTaxResult))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPayPeriod)
                                .addGap(71, 71, 71)))
                        .addContainerGap(287, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNext)
                        .addContainerGap())))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelPayPeriod)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalBasicSalary)
                            .addComponent(jLabelTotalBasicSalaryResult))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalGrossSalary)
                            .addComponent(jLabelTotalGrossSalaryResult))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalGovernmentContribution)
                            .addComponent(jLabelTotalGovernmentContributionResult))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalWithholdingTax)
                            .addComponent(jLabelTotalWithholdingTaxResult))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalDeduction)
                            .addComponent(jLabelTotalDeductionResult))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalNetSalary)
                            .addComponent(jLabelTotalNetSalaryResult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNext)
                            .addComponent(jButtonBack))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1EmployeeInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EmployeeInformationActionPerformed
         Access.accessEmployeeInformation(this.admin);
         this.setVisible(false);
    }//GEN-LAST:event_jButton1EmployeeInformationActionPerformed

    private void jButton6LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6LogOutActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6LogOutActionPerformed

    private void jButton3SelfServicePortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3SelfServicePortalActionPerformed
        Access.accessViewEmployeeDetails(this.admin, this.admin.getEmployeeID());
        this.setVisible(false);
    }//GEN-LAST:event_jButton3SelfServicePortalActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        Access.accessPayrollList(this.admin);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Access.accessPayrollNetPay(this.admin, this.payrollPayPeriod);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(PayrollSummaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Assuming you have a way to authenticate the user and create a valid User object
//    User loggedInUser = new Admin("adminUsername", "adminPassword");  // Example: Creating an Admin object

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new PayrollSummaryPage().setVisible(true); 
            
            // Pass the logged-in user to the constructor
//            new CompanyHomePage(loggedInUser).setVisible(true); 
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1EmployeeInformation;
    private javax.swing.JButton jButton3EmployeeRequest;
    private javax.swing.JButton jButton3SelfServicePortal;
    private javax.swing.JButton jButton4Payroll;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6LogOut;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabelPayPeriod;
    private javax.swing.JLabel jLabelTotalBasicSalary;
    private javax.swing.JLabel jLabelTotalBasicSalaryResult;
    private javax.swing.JLabel jLabelTotalDeduction;
    private javax.swing.JLabel jLabelTotalDeductionResult;
    private javax.swing.JLabel jLabelTotalGovernmentContribution;
    private javax.swing.JLabel jLabelTotalGovernmentContributionResult;
    private javax.swing.JLabel jLabelTotalGrossSalary;
    private javax.swing.JLabel jLabelTotalGrossSalaryResult;
    private javax.swing.JLabel jLabelTotalNetSalary;
    private javax.swing.JLabel jLabelTotalNetSalaryResult;
    private javax.swing.JLabel jLabelTotalWithholdingTax;
    private javax.swing.JLabel jLabelTotalWithholdingTaxResult;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
