/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import Class.TAT.Leave;
import Class.TAT.Overtime;
import java.util.Date;
import Class.UMS.CurrentUser;
import java.awt.Color;
import java.io.IOException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Charm
 */
public class RequestCenter extends javax.swing.JFrame {

    private CurrentUser currentUser;
    
    public RequestCenter(CurrentUser currentUser) {
        this.currentUser = currentUser;  // Set the currentUser object
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1RequestCenter = new javax.swing.JButton();
        jButton3AttendanceRecord = new javax.swing.JButton();
        jButton4Payslip = new javax.swing.JButton();
        jButton6LogOut = new javax.swing.JButton();
        jButton3TimeClock = new javax.swing.JButton();
        jButton4CompanyPortal = new javax.swing.JButton();
        jTabbedPane1SubmitOvertime = new javax.swing.JTabbedPane();
        jPanel3SubmitLeave = new javax.swing.JPanel();
        jDateChooser1StartDate = new com.toedter.calendar.JDateChooser();
        jDateChooser2EndDate = new com.toedter.calendar.JDateChooser();
        jLabel1StartDate = new javax.swing.JLabel();
        jLabel2EndDate = new javax.swing.JLabel();
        jComboBox1LeaveType = new javax.swing.JComboBox<>();
        jLabel3LeaveType = new javax.swing.JLabel();
        jLabel4TotalDays = new javax.swing.JLabel();
        jTextField1TotalDays = new javax.swing.JTextField();
        jLabel5Notes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Notes = new javax.swing.JTextArea();
        jButton1CalculateDays = new javax.swing.JButton();
        jButton1SubmitLeave = new javax.swing.JButton();
        jLabel1ValidationForLeave = new javax.swing.JLabel();
        jPanel4SubmitOvertime = new javax.swing.JPanel();
        jLabel1OvertimeDate = new javax.swing.JLabel();
        jDateChooser1Overtime = new com.toedter.calendar.JDateChooser();
        jLabel4OvertimeStart = new javax.swing.JLabel();
        jLabel5OvertimeEnd = new javax.swing.JLabel();
        jTextField4OvertimeEnd = new javax.swing.JTextField();
        jTextField5OvertimeStart = new javax.swing.JTextField();
        jLabel6TotalOvertime = new javax.swing.JLabel();
        jTextField1TotalOvertime = new javax.swing.JTextField();
        jButton1SubmitOvertime = new javax.swing.JButton();
        jComboBox1AMPM = new javax.swing.JComboBox<>();
        jComboBox2AMPM = new javax.swing.JComboBox<>();
        jLabel1ValidationErrors = new javax.swing.JLabel();
        jButton1Calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jButton1RequestCenter.setBackground(new java.awt.Color(0, 102, 153));
        jButton1RequestCenter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1RequestCenter.setForeground(new java.awt.Color(255, 255, 255));
        jButton1RequestCenter.setText("Request Center");
        jButton1RequestCenter.setBorder(null);

        jButton3AttendanceRecord.setBackground(new java.awt.Color(0, 102, 153));
        jButton3AttendanceRecord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3AttendanceRecord.setForeground(new java.awt.Color(255, 255, 255));
        jButton3AttendanceRecord.setText("Attendance Record");
        jButton3AttendanceRecord.setBorder(null);
        jButton3AttendanceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3AttendanceRecordActionPerformed(evt);
            }
        });

        jButton4Payslip.setBackground(new java.awt.Color(0, 102, 153));
        jButton4Payslip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4Payslip.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Payslip.setText("Payslip");
        jButton4Payslip.setBorder(null);

        jButton6LogOut.setBackground(new java.awt.Color(0, 102, 153));
        jButton6LogOut.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton6LogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButton6LogOut.setText("Log Out");
        jButton6LogOut.setBorder(null);
        jButton6LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6LogOutActionPerformed(evt);
            }
        });

        jButton3TimeClock.setBackground(new java.awt.Color(0, 102, 153));
        jButton3TimeClock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3TimeClock.setForeground(new java.awt.Color(255, 255, 255));
        jButton3TimeClock.setText("Time Clock");
        jButton3TimeClock.setBorder(null);
        jButton3TimeClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3TimeClockActionPerformed(evt);
            }
        });

        jButton4CompanyPortal.setBackground(new java.awt.Color(0, 102, 153));
        jButton4CompanyPortal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4CompanyPortal.setForeground(new java.awt.Color(255, 255, 255));
        jButton4CompanyPortal.setText("Company Portal");
        jButton4CompanyPortal.setBorder(null);
        jButton4CompanyPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4CompanyPortalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1RequestCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3AttendanceRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4Payslip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton6LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton3TimeClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButton4CompanyPortal, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton3TimeClock)
                .addGap(37, 37, 37)
                .addComponent(jButton3AttendanceRecord)
                .addGap(37, 37, 37)
                .addComponent(jButton1RequestCenter)
                .addGap(34, 34, 34)
                .addComponent(jButton4Payslip)
                .addGap(37, 37, 37)
                .addComponent(jButton4CompanyPortal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6LogOut)
                .addContainerGap())
        );

        jLabel1StartDate.setText("Start Date:");

        jLabel2EndDate.setText("End Date:");

        jComboBox1LeaveType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacation ", "Sick ", "Emergency", "Maternity", "Paternity", "Bereavement" }));

        jLabel3LeaveType.setText("Leave Type:");

        jLabel4TotalDays.setText("Total Days:");

        jTextField1TotalDays.setEditable(false);

        jLabel5Notes.setText("Notes:");

        jTextArea1Notes.setColumns(20);
        jTextArea1Notes.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Notes);

        jButton1CalculateDays.setText("Calculate");
        jButton1CalculateDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CalculateDaysActionPerformed(evt);
            }
        });

        jButton1SubmitLeave.setText("Submit");
        jButton1SubmitLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SubmitLeaveActionPerformed(evt);
            }
        });

        jLabel1ValidationForLeave.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3SubmitLeaveLayout = new javax.swing.GroupLayout(jPanel3SubmitLeave);
        jPanel3SubmitLeave.setLayout(jPanel3SubmitLeaveLayout);
        jPanel3SubmitLeaveLayout.setHorizontalGroup(
            jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3SubmitLeaveLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4TotalDays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3LeaveType, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addComponent(jLabel1StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5Notes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1LeaveType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2EndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1StartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3SubmitLeaveLayout.createSequentialGroup()
                        .addComponent(jTextField1TotalDays, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1CalculateDays, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3SubmitLeaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1ValidationForLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3SubmitLeaveLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButton1SubmitLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel3SubmitLeaveLayout.setVerticalGroup(
            jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3SubmitLeaveLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1StartDate)
                    .addComponent(jDateChooser1StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2EndDate)
                    .addComponent(jDateChooser2EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1LeaveType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3LeaveType))
                .addGap(40, 40, 40)
                .addGroup(jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4TotalDays)
                    .addComponent(jTextField1TotalDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1CalculateDays))
                .addGap(14, 14, 14)
                .addComponent(jLabel1ValidationForLeave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3SubmitLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5Notes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1SubmitLeave)
                .addGap(26, 26, 26))
        );

        jTabbedPane1SubmitOvertime.addTab("Leave", jPanel3SubmitLeave);

        jLabel1OvertimeDate.setText("Date:");

        jLabel4OvertimeStart.setText("Start time: ");

        jLabel5OvertimeEnd.setText("End time: ");

        jLabel6TotalOvertime.setText("Total overtime hours:");

        jTextField1TotalOvertime.setEditable(false);

        jButton1SubmitOvertime.setText("Submit");
        jButton1SubmitOvertime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SubmitOvertimeActionPerformed(evt);
            }
        });

        jComboBox1AMPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        jComboBox2AMPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        jButton1Calculate.setText("Calculate");
        jButton1Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4SubmitOvertimeLayout = new javax.swing.GroupLayout(jPanel4SubmitOvertime);
        jPanel4SubmitOvertime.setLayout(jPanel4SubmitOvertimeLayout);
        jPanel4SubmitOvertimeLayout.setHorizontalGroup(
            jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                        .addComponent(jLabel6TotalOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1TotalOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                        .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1OvertimeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4OvertimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField5OvertimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1AMPM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1Overtime, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                        .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                                .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                                        .addComponent(jLabel5OvertimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4OvertimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1ValidationErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4SubmitOvertimeLayout.createSequentialGroup()
                                .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1Calculate, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(jButton1SubmitOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)))
                        .addComponent(jComboBox2AMPM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel4SubmitOvertimeLayout.setVerticalGroup(
            jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4SubmitOvertimeLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1OvertimeDate)
                    .addComponent(jDateChooser1Overtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4OvertimeStart)
                    .addComponent(jTextField5OvertimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1AMPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5OvertimeEnd)
                    .addComponent(jTextField4OvertimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2AMPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4SubmitOvertimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6TotalOvertime)
                    .addComponent(jTextField1TotalOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel1ValidationErrors)
                .addGap(18, 18, 18)
                .addComponent(jButton1Calculate)
                .addGap(18, 18, 18)
                .addComponent(jButton1SubmitOvertime)
                .addContainerGap())
        );

        jTabbedPane1SubmitOvertime.addTab("Overtime", jPanel4SubmitOvertime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1SubmitOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTabbedPane1SubmitOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6LogOutActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6LogOutActionPerformed

    private void jButton1SubmitOvertimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SubmitOvertimeActionPerformed
        // 1. Date validation
        Date overtimeDate = jDateChooser1Overtime.getDate();
        if (overtimeDate == null) {
            showValidationError("Invalid entry");
            return;
        }

        // 2. Time validation (start and end time format and logical validation)
        String startTime = jTextField5OvertimeStart.getText();
        String endTime = jTextField4OvertimeEnd.getText();

        // 3. Create a Overtime object to use time validation methods 
        Overtime validation = null;
            try {
                validation = new Overtime("OT", overtimeDate, startTime, endTime, overtimeDate);
            } catch (IOException ex) {
                Logger.getLogger(RequestCenter.class.getName()).log(Level.SEVERE, null, ex);
            }

        // 4. Check if the time format is valid (HH:MM)  
        if (!validation.isValidTimeFormat(startTime)|| !validation.isValidTimeFormat(endTime)) {
            showValidationError("Time must be in HH:MM format.");
            return;
        }

        if (validation.compareTimes(startTime, endTime) > 0 || startTime.equals(endTime)) {
            showValidationError("Invalid entry");
            return;
        }

        // OT date cannot be a future date
        LocalDate overtimeLocalDate = overtimeDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (overtimeLocalDate.isAfter(LocalDate.now())) {
            showValidationError("Invalid entry");
            return;
        }

        // 5. Combine time with AM/PM
        startTime += " " + jComboBox1AMPM.getSelectedItem();
        endTime += " " + jComboBox2AMPM.getSelectedItem();

        // 6. Process the request if everything is valid
        // Create an Overtime instance
        Overtime overtime = null;
            try {
                overtime = new Overtime("OT", overtimeDate, startTime, endTime, overtimeDate);
            } catch (IOException ex) {
                Logger.getLogger(RequestCenter.class.getName()).log(Level.SEVERE, null, ex);
            }

        // 7. Calculate total overtime
        overtime.calculateTotalOvertime();

        // 8. Process the request (save to CSV)
        overtime.processRequest();

        // 9. Clear the fields after submission
        jTextField5OvertimeStart.setText("");
        jTextField4OvertimeEnd.setText("");
        jComboBox1AMPM.setSelectedIndex(0);
        jComboBox2AMPM.setSelectedIndex(0); 
        jDateChooser1Overtime.setDate(null);  
        jLabel1ValidationErrors.setText("");
        jTextField1TotalOvertime.setText(""); 
        
        // Clear any previous error messages
        jLabel1ValidationErrors.setText("");
    }

    // Method to show validation error message
    private void showValidationError(String message) {
        // Display validation error message
        jLabel1ValidationErrors.setText(message);
        jLabel1ValidationErrors.setForeground(Color.RED);
    }//GEN-LAST:event_jButton1SubmitOvertimeActionPerformed

    private void jButton1CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CalculateActionPerformed
        // 1. Date validation
        Date overtimeDate = jDateChooser1Overtime.getDate();
        if (overtimeDate == null) {
           showValidationError("Invalid entry");
           return;
        }

        // 2. Time validation (start and end time format and logical validation)
        String startTime = jTextField5OvertimeStart.getText();
        String endTime = jTextField4OvertimeEnd.getText();

        // 3. Create a Request object to use time validation methods 
        Overtime validation = null;
        try {
            validation = new Overtime("OT", overtimeDate, startTime, endTime, overtimeDate);
        } catch (IOException ex) {
            Logger.getLogger(RequestCenter.class.getName()).log(Level.SEVERE, null, ex);
        }

        // 4. Check if the time format is valid (HH:MM)
        if (!validation.isValidTimeFormat(startTime)|| !validation.isValidTimeFormat(endTime)) {
           showValidationError("Time must be in HH:MM format.");
           return;
        }

        // 5. End time cannot be before the start time
        if (validation.compareTimes(startTime, endTime) > 0 || startTime.equals(endTime)) {
           showValidationError("Invalid entry");
           return;
        }
        
        // OT date cannot be a future date
        LocalDate overtimeLocalDate = overtimeDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (overtimeLocalDate.isAfter(LocalDate.now())) {
            showValidationError("Invalid entry");
            return;
        }

        // 6. Combine time with AM/PM
        startTime += " " + jComboBox1AMPM.getSelectedItem();
        endTime += " " + jComboBox2AMPM.getSelectedItem();

        // 7. Calculate total overtime 
        Overtime overtime = null;
        try {
            overtime = new Overtime("OT",overtimeDate, startTime, endTime, overtimeDate);
        } catch (IOException ex) {
            Logger.getLogger(RequestCenter.class.getName()).log(Level.SEVERE, null, ex);
        }

        overtime.calculateTotalOvertime();

        // 8. Display the result in the text field (total overtime hours)
        jTextField1TotalOvertime.setText(String.format("%.2f", overtime.totalOvertime));

        // 9. Clear any previous error messages
        jLabel1ValidationErrors.setText("");
    }//GEN-LAST:event_jButton1CalculateActionPerformed

    private void jButton1CalculateDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CalculateDaysActionPerformed
        // Clear previous validation message
        jLabel1ValidationForLeave.setText("");

        // 1. Get the start date and end date 
        Date startDate = jDateChooser1StartDate.getDate();
        Date endDate = jDateChooser2EndDate.getDate();

        // 2. Check if both start date and end date are selected
        if ((startDate == null || endDate == null) || ((endDate.before(startDate))) ) {
            jLabel1ValidationForLeave.setText("Invalid entry");
            return;
        }

        // 3. Retrieve leave type and notes 
        String leaveType = (String) jComboBox1LeaveType.getSelectedItem(); 
        String notes = jTextArea1Notes.getText(); 

        // 4. Get the current date as requestDate 
        Date requestDate = new Date();

        // 5. Create the Leave object with all required parameters
        Leave leaveRequest = null;
            try {
                leaveRequest = new Leave(startDate, endDate, leaveType, notes, requestDate);
            } catch (IOException ex) {
                Logger.getLogger(RequestCenter.class.getName()).log(Level.SEVERE, null, ex);
            }

        // 6. Calculate the total leave days 
        double totalDays = leaveRequest.calculateTotalDays(startDate, endDate);

        // 7. Display the total days in the text field
        jTextField1TotalDays.setText(String.format("%.2f", totalDays));
    }//GEN-LAST:event_jButton1CalculateDaysActionPerformed

    private void jButton1SubmitLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SubmitLeaveActionPerformed
        // 1. Get the start date and end date 
        Date startDate = jDateChooser1StartDate.getDate();
        Date endDate = jDateChooser2EndDate.getDate();

        // 2. Check if both start date and end date are selected
        if ((startDate == null || endDate == null) || ((endDate.before(startDate) || endDate.equals(startDate))) ) {
            jLabel1ValidationForLeave.setText("Invalid entry");
            return; 
        }

        // 3. Retrieve leave type and notes 
        String leaveType = (String) jComboBox1LeaveType.getSelectedItem();
        String notes = jTextArea1Notes.getText(); 

        // 4. Get the current date as requestDate 
        Date requestDate = new Date();

        // 5. Create the Leave object with all required parameters
        Leave leaveRequest = null;
            try {
                leaveRequest = new Leave(startDate, endDate, leaveType, notes, requestDate);
            } catch (IOException ex) {
                Logger.getLogger(RequestCenter.class.getName()).log(Level.SEVERE, null, ex);
            }

        // 6. Process the leave request 
        leaveRequest.processRequest();

        // 7. Clear fields for new submission
        jDateChooser1StartDate.setDate(null);
        jDateChooser2EndDate.setDate(null);
        jComboBox1LeaveType.setSelectedIndex(0); 
        jTextArea1Notes.setText(""); 
        jTextField1TotalDays.setText(""); 
    }//GEN-LAST:event_jButton1SubmitLeaveActionPerformed

    private void jButton3TimeClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3TimeClockActionPerformed
        EmployeeDashboard employeeDashboard = new EmployeeDashboard(currentUser);
        employeeDashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3TimeClockActionPerformed

    private void jButton4CompanyPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4CompanyPortalActionPerformed
        CompanyHomePage companyHomePage = new CompanyHomePage(currentUser);
        companyHomePage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4CompanyPortalActionPerformed

    private void jButton3AttendanceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3AttendanceRecordActionPerformed
        AttendanceRecord attendancerecord = new AttendanceRecord();
        attendancerecord.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3AttendanceRecordActionPerformed

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel
        Look and feel setting code (optional)*/

        /*Create and display the form*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Calculate;
    private javax.swing.JButton jButton1CalculateDays;
    private javax.swing.JButton jButton1RequestCenter;
    private javax.swing.JButton jButton1SubmitLeave;
    private javax.swing.JButton jButton1SubmitOvertime;
    private javax.swing.JButton jButton3AttendanceRecord;
    private javax.swing.JButton jButton3TimeClock;
    private javax.swing.JButton jButton4CompanyPortal;
    private javax.swing.JButton jButton4Payslip;
    private javax.swing.JButton jButton6LogOut;
    private javax.swing.JComboBox<String> jComboBox1AMPM;
    private javax.swing.JComboBox<String> jComboBox1LeaveType;
    private javax.swing.JComboBox<String> jComboBox2AMPM;
    private com.toedter.calendar.JDateChooser jDateChooser1Overtime;
    private com.toedter.calendar.JDateChooser jDateChooser1StartDate;
    private com.toedter.calendar.JDateChooser jDateChooser2EndDate;
    private javax.swing.JLabel jLabel1OvertimeDate;
    private javax.swing.JLabel jLabel1StartDate;
    private javax.swing.JLabel jLabel1ValidationErrors;
    private javax.swing.JLabel jLabel1ValidationForLeave;
    private javax.swing.JLabel jLabel2EndDate;
    private javax.swing.JLabel jLabel3LeaveType;
    private javax.swing.JLabel jLabel4OvertimeStart;
    private javax.swing.JLabel jLabel4TotalDays;
    private javax.swing.JLabel jLabel5Notes;
    private javax.swing.JLabel jLabel5OvertimeEnd;
    private javax.swing.JLabel jLabel6TotalOvertime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3SubmitLeave;
    private javax.swing.JPanel jPanel4SubmitOvertime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1SubmitOvertime;
    private javax.swing.JTextArea jTextArea1Notes;
    private javax.swing.JTextField jTextField1TotalDays;
    private javax.swing.JTextField jTextField1TotalOvertime;
    private javax.swing.JTextField jTextField4OvertimeEnd;
    private javax.swing.JTextField jTextField5OvertimeStart;
    // End of variables declaration//GEN-END:variables


}
